### ISSUE TITLE
build bot no longer updating

### ISSUE THREAD

**Issue by Mr-Jake** [diablodiab/libretro-scummvm-backend#22]
It seems the build bot [http://build.bot.nu/] is no longer updating. The last build is from August 14 2022. 

Is there a problem or if it was discontinued, is there another location to get builds?

**Comment by diablodiab** [comment]
Yes, I had to stop the automatic builds because I needed the processing power elsewhere.It is still pretty easy to build the cores manually, so I'm counting on those interested in this customized core to try that approach.

Hopefully at some point, the official ScummVM core will have more updated builds.
